### ISSUE TITLE
Add Game-Over

### ISSUE THREAD

**Issue by The-Phoenics** [Karansemwal/Snake-Game#1]
Currently there's no game-over feature in the game which makes the game pretty aimless for now. 

Add a game over feature :
Game should start over whenever snake collides with it's body

**Comment by balsa-asanovic** [comment]
I'd also like to work on this issue.

It'd be my second contribution, after this [one](https://github.com/Karansemwal/Snake-Game/issues/2) :D

**Comment by The-Phoenics** [comment]
Welome to project @balsa-asanovic. Feel free to take full control & make suitable changes.

**Comment by balsa-asanovic** [comment]
Thanks a lot!

**Comment by balsa-asanovic** [comment]
Addressed in pull request #4
