### ISSUE TITLE
Add Score

### ISSUE THREAD

**Issue by The-Phoenics** [Karansemwal/Snake-Game#2]
Add a score feature to the game :
Create a variable to keep track of the score, increment score by a constant value whenever the snake eats the fruit
Create a `sf::Text` and `sf::Font` objects `m_score` and `m_scoreFont` respectively. Load a font into `m_scoreFont` object. 
Initialize `m_score` with value **0** and update the value of `m_score` along with score.
( use any suitable font )

**Comment by balsa-asanovic** [comment]
Hey there, I'd like to work on this issue, can you assign it to me?

It'd be my first open-source contribution, I hope you don't mind :D

**Comment by The-Phoenics** [comment]
@balsa-asanovic why not, go for it. 
Feel free to make any suitable changes needed.

**Comment by balsa-asanovic** [comment]
Addressed in pull request #4
