### ISSUE TITLE
Add full screen possibility

### ISSUE THREAD

**Issue by alh45011** [Karansemwal/Snake-Game#3]
Hi guys,

Can I join this project? I could implement full screen, random obstacles or something else.

**Comment by The-Phoenics** [comment]
Hi @alh45011, thank you for choosing this project.
Yes, currently the game window isn't resizable. Feel free to work on this issue.

The idea of **Random obstactles** would fall under the category of *implementing a game-map*, which is also currently lacking in the game. You can create a new issue regarding that and start working on it.
